/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ChainDepositContract {
  export type DepositStruct = {
    id: BigNumberish;
    user: AddressLike;
    token: AddressLike;
    amount: BigNumberish;
    btcEquivalent: BigNumberish;
    timestamp: BigNumberish;
    processed: boolean;
  };

  export type DepositStructOutput = [
    id: bigint,
    user: string,
    token: string,
    amount: bigint,
    btcEquivalent: bigint,
    timestamp: bigint,
    processed: boolean
  ] & {
    id: bigint;
    user: string;
    token: string;
    amount: bigint;
    btcEquivalent: bigint;
    timestamp: bigint;
    processed: boolean;
  };
}

export interface ChainDepositContractInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSupportedToken"
      | "calculateBtcEquivalent"
      | "createIntent"
      | "deposit"
      | "depositManager"
      | "deposits"
      | "emergencyWithdraw"
      | "getDeposit"
      | "getStats"
      | "getUserDeposits"
      | "nextDepositId"
      | "owner"
      | "priceOracle"
      | "removeSupportedToken"
      | "renounceOwnership"
      | "supportedTokens"
      | "tokenDecimals"
      | "totalBtcEquivalent"
      | "totalDeposits"
      | "transferOwnership"
      | "userDeposits"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BtcEquivalentCalculated"
      | "DepositCreated"
      | "IntentCreated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSupportedToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateBtcEquivalent",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createIntent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDeposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getStats", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getUserDeposits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextDepositId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupportedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenDecimals",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBtcEquivalent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalDeposits",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userDeposits",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateBtcEquivalent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIntent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDeposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextDepositId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenDecimals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBtcEquivalent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDeposits",
    data: BytesLike
  ): Result;
}

export namespace BtcEquivalentCalculatedEvent {
  export type InputTuple = [
    token: AddressLike,
    amount: BigNumberish,
    btcEquivalent: BigNumberish
  ];
  export type OutputTuple = [
    token: string,
    amount: bigint,
    btcEquivalent: bigint
  ];
  export interface OutputObject {
    token: string;
    amount: bigint;
    btcEquivalent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositCreatedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    user: AddressLike,
    token: AddressLike,
    amount: BigNumberish,
    btcEquivalent: BigNumberish
  ];
  export type OutputTuple = [
    depositId: bigint,
    user: string,
    token: string,
    amount: bigint,
    btcEquivalent: bigint
  ];
  export interface OutputObject {
    depositId: bigint;
    user: string;
    token: string;
    amount: bigint;
    btcEquivalent: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IntentCreatedEvent {
  export type InputTuple = [
    depositId: BigNumberish,
    activationId: BigNumberish,
    intentData: string
  ];
  export type OutputTuple = [
    depositId: bigint,
    activationId: bigint,
    intentData: string
  ];
  export interface OutputObject {
    depositId: bigint;
    activationId: bigint;
    intentData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChainDepositContract extends BaseContract {
  connect(runner?: ContractRunner | null): ChainDepositContract;
  waitForDeployment(): Promise<this>;

  interface: ChainDepositContractInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSupportedToken: TypedContractMethod<
    [token: AddressLike, decimals: BigNumberish],
    [void],
    "nonpayable"
  >;

  calculateBtcEquivalent: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  createIntent: TypedContractMethod<
    [depositId: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  deposit: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  depositManager: TypedContractMethod<[], [string], "view">;

  deposits: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, boolean] & {
        id: bigint;
        user: string;
        token: string;
        amount: bigint;
        btcEquivalent: bigint;
        timestamp: bigint;
        processed: boolean;
      }
    ],
    "view"
  >;

  emergencyWithdraw: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDeposit: TypedContractMethod<
    [depositId: BigNumberish],
    [ChainDepositContract.DepositStructOutput],
    "view"
  >;

  getStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalDepositsCount: bigint;
        totalBtcEquivalentAmount: bigint;
        nextDepositIdValue: bigint;
      }
    ],
    "view"
  >;

  getUserDeposits: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  nextDepositId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  removeSupportedToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  supportedTokens: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  tokenDecimals: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  totalBtcEquivalent: TypedContractMethod<[], [bigint], "view">;

  totalDeposits: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userDeposits: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSupportedToken"
  ): TypedContractMethod<
    [token: AddressLike, decimals: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "calculateBtcEquivalent"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createIntent"
  ): TypedContractMethod<[depositId: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "deposits"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, bigint, bigint, bigint, boolean] & {
        id: bigint;
        user: string;
        token: string;
        amount: bigint;
        btcEquivalent: bigint;
        timestamp: bigint;
        processed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDeposit"
  ): TypedContractMethod<
    [depositId: BigNumberish],
    [ChainDepositContract.DepositStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        totalDepositsCount: bigint;
        totalBtcEquivalentAmount: bigint;
        nextDepositIdValue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserDeposits"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "nextDepositId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeSupportedToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tokenDecimals"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalBtcEquivalent"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalDeposits"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userDeposits"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "BtcEquivalentCalculated"
  ): TypedContractEvent<
    BtcEquivalentCalculatedEvent.InputTuple,
    BtcEquivalentCalculatedEvent.OutputTuple,
    BtcEquivalentCalculatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositCreated"
  ): TypedContractEvent<
    DepositCreatedEvent.InputTuple,
    DepositCreatedEvent.OutputTuple,
    DepositCreatedEvent.OutputObject
  >;
  getEvent(
    key: "IntentCreated"
  ): TypedContractEvent<
    IntentCreatedEvent.InputTuple,
    IntentCreatedEvent.OutputTuple,
    IntentCreatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "BtcEquivalentCalculated(address,uint256,uint256)": TypedContractEvent<
      BtcEquivalentCalculatedEvent.InputTuple,
      BtcEquivalentCalculatedEvent.OutputTuple,
      BtcEquivalentCalculatedEvent.OutputObject
    >;
    BtcEquivalentCalculated: TypedContractEvent<
      BtcEquivalentCalculatedEvent.InputTuple,
      BtcEquivalentCalculatedEvent.OutputTuple,
      BtcEquivalentCalculatedEvent.OutputObject
    >;

    "DepositCreated(uint256,address,address,uint256,uint256)": TypedContractEvent<
      DepositCreatedEvent.InputTuple,
      DepositCreatedEvent.OutputTuple,
      DepositCreatedEvent.OutputObject
    >;
    DepositCreated: TypedContractEvent<
      DepositCreatedEvent.InputTuple,
      DepositCreatedEvent.OutputTuple,
      DepositCreatedEvent.OutputObject
    >;

    "IntentCreated(uint256,uint256,string)": TypedContractEvent<
      IntentCreatedEvent.InputTuple,
      IntentCreatedEvent.OutputTuple,
      IntentCreatedEvent.OutputObject
    >;
    IntentCreated: TypedContractEvent<
      IntentCreatedEvent.InputTuple,
      IntentCreatedEvent.OutputTuple,
      IntentCreatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
