/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DepositManager {
  export type ActivationStruct = {
    id: BigNumberish;
    user: AddressLike;
    amount: BigNumberish;
    btcEquivalent: BigNumberish;
    lockedPrice: BigNumberish;
    timestamp: BigNumberish;
    processed: boolean;
    settled: boolean;
  };

  export type ActivationStructOutput = [
    id: bigint,
    user: string,
    amount: bigint,
    btcEquivalent: bigint,
    lockedPrice: bigint,
    timestamp: bigint,
    processed: boolean,
    settled: boolean
  ] & {
    id: bigint;
    user: string;
    amount: bigint;
    btcEquivalent: bigint;
    lockedPrice: bigint;
    timestamp: bigint;
    processed: boolean;
    settled: boolean;
  };
}

export interface DepositManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activations"
      | "btcPoolBalance"
      | "currentProcessingId"
      | "emergencyReset"
      | "getActivation"
      | "getQueueStatus"
      | "getUserActivations"
      | "maxQueueSize"
      | "nextActivationId"
      | "owner"
      | "priceOracle"
      | "processNextActivation"
      | "processingPaused"
      | "receiveDeposit"
      | "renounceOwnership"
      | "setMaxQueueSize"
      | "setProcessingPaused"
      | "settleActivation"
      | "transferOwnership"
      | "updateBtcPoolBalance"
      | "userActivations"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActivationProcessed"
      | "BtcPoolUpdated"
      | "DepositReceived"
      | "OwnershipTransferred"
      | "SettlementFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activations",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "btcPoolBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentProcessingId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyReset",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActivation",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getQueueStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserActivations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxQueueSize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextActivationId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processNextActivation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processingPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiveDeposit",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxQueueSize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setProcessingPaused",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "settleActivation",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBtcPoolBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userActivations",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "btcPoolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentProcessingId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyReset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActivation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getQueueStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserActivations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxQueueSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextActivationId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processNextActivation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processingPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxQueueSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProcessingPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleActivation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBtcPoolBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userActivations",
    data: BytesLike
  ): Result;
}

export namespace ActivationProcessedEvent {
  export type InputTuple = [
    activationId: BigNumberish,
    newPrice: BigNumberish,
    settled: boolean
  ];
  export type OutputTuple = [
    activationId: bigint,
    newPrice: bigint,
    settled: boolean
  ];
  export interface OutputObject {
    activationId: bigint;
    newPrice: bigint;
    settled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BtcPoolUpdatedEvent {
  export type InputTuple = [newBalance: BigNumberish];
  export type OutputTuple = [newBalance: bigint];
  export interface OutputObject {
    newBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositReceivedEvent {
  export type InputTuple = [
    activationId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    btcEquivalent: BigNumberish,
    lockedPrice: BigNumberish
  ];
  export type OutputTuple = [
    activationId: bigint,
    user: string,
    amount: bigint,
    btcEquivalent: bigint,
    lockedPrice: bigint
  ];
  export interface OutputObject {
    activationId: bigint;
    user: string;
    amount: bigint;
    btcEquivalent: bigint;
    lockedPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementFailedEvent {
  export type InputTuple = [activationId: BigNumberish];
  export type OutputTuple = [activationId: bigint];
  export interface OutputObject {
    activationId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DepositManager extends BaseContract {
  connect(runner?: ContractRunner | null): DepositManager;
  waitForDeployment(): Promise<this>;

  interface: DepositManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activations: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        id: bigint;
        user: string;
        amount: bigint;
        btcEquivalent: bigint;
        lockedPrice: bigint;
        timestamp: bigint;
        processed: boolean;
        settled: boolean;
      }
    ],
    "view"
  >;

  btcPoolBalance: TypedContractMethod<[], [bigint], "view">;

  currentProcessingId: TypedContractMethod<[], [bigint], "view">;

  emergencyReset: TypedContractMethod<[], [void], "nonpayable">;

  getActivation: TypedContractMethod<
    [activationId: BigNumberish],
    [DepositManager.ActivationStructOutput],
    "view"
  >;

  getQueueStatus: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        totalActivations: bigint;
        processedActivations: bigint;
        settledActivations: bigint;
        isProcessingPaused: boolean;
      }
    ],
    "view"
  >;

  getUserActivations: TypedContractMethod<
    [user: AddressLike],
    [bigint[]],
    "view"
  >;

  maxQueueSize: TypedContractMethod<[], [bigint], "view">;

  nextActivationId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  priceOracle: TypedContractMethod<[], [string], "view">;

  processNextActivation: TypedContractMethod<[], [void], "nonpayable">;

  processingPaused: TypedContractMethod<[], [boolean], "view">;

  receiveDeposit: TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, btcEquivalent: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMaxQueueSize: TypedContractMethod<
    [newSize: BigNumberish],
    [void],
    "nonpayable"
  >;

  setProcessingPaused: TypedContractMethod<
    [paused: boolean],
    [void],
    "nonpayable"
  >;

  settleActivation: TypedContractMethod<
    [activationId: BigNumberish, settlementSuccess: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateBtcPoolBalance: TypedContractMethod<
    [newBalance: BigNumberish],
    [void],
    "nonpayable"
  >;

  userActivations: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activations"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        id: bigint;
        user: string;
        amount: bigint;
        btcEquivalent: bigint;
        lockedPrice: bigint;
        timestamp: bigint;
        processed: boolean;
        settled: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "btcPoolBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentProcessingId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "emergencyReset"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActivation"
  ): TypedContractMethod<
    [activationId: BigNumberish],
    [DepositManager.ActivationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getQueueStatus"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, boolean] & {
        totalActivations: bigint;
        processedActivations: bigint;
        settledActivations: bigint;
        isProcessingPaused: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserActivations"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "maxQueueSize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextActivationId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "priceOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processNextActivation"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "processingPaused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "receiveDeposit"
  ): TypedContractMethod<
    [user: AddressLike, amount: BigNumberish, btcEquivalent: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxQueueSize"
  ): TypedContractMethod<[newSize: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setProcessingPaused"
  ): TypedContractMethod<[paused: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleActivation"
  ): TypedContractMethod<
    [activationId: BigNumberish, settlementSuccess: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateBtcPoolBalance"
  ): TypedContractMethod<[newBalance: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userActivations"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ActivationProcessed"
  ): TypedContractEvent<
    ActivationProcessedEvent.InputTuple,
    ActivationProcessedEvent.OutputTuple,
    ActivationProcessedEvent.OutputObject
  >;
  getEvent(
    key: "BtcPoolUpdated"
  ): TypedContractEvent<
    BtcPoolUpdatedEvent.InputTuple,
    BtcPoolUpdatedEvent.OutputTuple,
    BtcPoolUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DepositReceived"
  ): TypedContractEvent<
    DepositReceivedEvent.InputTuple,
    DepositReceivedEvent.OutputTuple,
    DepositReceivedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SettlementFailed"
  ): TypedContractEvent<
    SettlementFailedEvent.InputTuple,
    SettlementFailedEvent.OutputTuple,
    SettlementFailedEvent.OutputObject
  >;

  filters: {
    "ActivationProcessed(uint256,uint256,bool)": TypedContractEvent<
      ActivationProcessedEvent.InputTuple,
      ActivationProcessedEvent.OutputTuple,
      ActivationProcessedEvent.OutputObject
    >;
    ActivationProcessed: TypedContractEvent<
      ActivationProcessedEvent.InputTuple,
      ActivationProcessedEvent.OutputTuple,
      ActivationProcessedEvent.OutputObject
    >;

    "BtcPoolUpdated(uint256)": TypedContractEvent<
      BtcPoolUpdatedEvent.InputTuple,
      BtcPoolUpdatedEvent.OutputTuple,
      BtcPoolUpdatedEvent.OutputObject
    >;
    BtcPoolUpdated: TypedContractEvent<
      BtcPoolUpdatedEvent.InputTuple,
      BtcPoolUpdatedEvent.OutputTuple,
      BtcPoolUpdatedEvent.OutputObject
    >;

    "DepositReceived(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      DepositReceivedEvent.InputTuple,
      DepositReceivedEvent.OutputTuple,
      DepositReceivedEvent.OutputObject
    >;
    DepositReceived: TypedContractEvent<
      DepositReceivedEvent.InputTuple,
      DepositReceivedEvent.OutputTuple,
      DepositReceivedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SettlementFailed(uint256)": TypedContractEvent<
      SettlementFailedEvent.InputTuple,
      SettlementFailedEvent.OutputTuple,
      SettlementFailedEvent.OutputObject
    >;
    SettlementFailed: TypedContractEvent<
      SettlementFailedEvent.InputTuple,
      SettlementFailedEvent.OutputTuple,
      SettlementFailedEvent.OutputObject
    >;
  };
}
