/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as xmblTokenSol from "./XMBLToken.sol";
export type { xmblTokenSol };
export type { ChainDepositContract } from "./ChainDepositContract";
export type { DepositManager } from "./DepositManager";
export type { PriceOracle } from "./PriceOracle";
