/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChainDepositContract } from "./ChainDepositContract";
export type { DepositManager } from "./DepositManager";
export type { PriceOracle } from "./PriceOracle";
export type { XMBLToken } from "./XMBLToken";
