/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "COIN_DIVIDE"
      | "COIN_RELEASE_TARGET"
      | "COIN_SUPPLY"
      | "GROWTH_FACTOR"
      | "NETWORK_FEE_PERCENT"
      | "PHI"
      | "SATOSHI_PRECISION"
      | "STARTING_PRICE"
      | "activateBulkTokens"
      | "activateToken"
      | "activationCount"
      | "activationPrices"
      | "activationSettled"
      | "btcUsdPriceId"
      | "calculateBulkCost"
      | "calculateNetworkFee"
      | "calculatePrice"
      | "currentPrice"
      | "deactivateToken"
      | "getBtcPrice"
      | "getCoinDistributionStatus"
      | "getCurrentPrice"
      | "getTokenomicsState"
      | "processActivationWithSettlement"
      | "proofOfFaith"
      | "pyth"
      | "setTokensMinted"
      | "tokensMinted"
      | "updatePrice"
      | "xyDivisor"
      | "xyNextAmount"
      | "xyReleaseTarget"
      | "xyReleased"
      | "xyRemaining"
      | "xymMinted"
      | "xymNextPrice"
      | "xymPrevPrice"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActivationProcessed"
      | "CoinsReleased"
      | "PriceUpdated"
      | "SettlementFailed"
      | "TokenomicsUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "COIN_DIVIDE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COIN_RELEASE_TARGET",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "COIN_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "GROWTH_FACTOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NETWORK_FEE_PERCENT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PHI", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "SATOSHI_PRECISION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "STARTING_PRICE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activateBulkTokens",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activateToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activationCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activationPrices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activationSettled",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "btcUsdPriceId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "calculateBulkCost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateNetworkFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculatePrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBtcPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCoinDistributionStatus",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenomicsState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "processActivationWithSettlement",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "proofOfFaith",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pyth", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setTokensMinted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokensMinted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "xyDivisor", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "xyNextAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xyReleaseTarget",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xyReleased",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xyRemaining",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "xymMinted", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "xymNextPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "xymPrevPrice",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "COIN_DIVIDE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COIN_RELEASE_TARGET",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "COIN_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "GROWTH_FACTOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NETWORK_FEE_PERCENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "PHI", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "SATOSHI_PRECISION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "STARTING_PRICE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateBulkTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activateToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activationCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activationPrices",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activationSettled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "btcUsdPriceId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateBulkCost",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculateNetworkFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calculatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBtcPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCoinDistributionStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenomicsState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "processActivationWithSettlement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proofOfFaith",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pyth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTokensMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokensMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xyDivisor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "xyNextAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xyReleaseTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xyReleased", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "xyRemaining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "xymMinted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "xymNextPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "xymPrevPrice",
    data: BytesLike
  ): Result;
}

export namespace ActivationProcessedEvent {
  export type InputTuple = [
    activationId: BigNumberish,
    price: BigNumberish,
    settled: boolean
  ];
  export type OutputTuple = [
    activationId: bigint,
    price: bigint,
    settled: boolean
  ];
  export interface OutputObject {
    activationId: bigint;
    price: bigint;
    settled: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoinsReleasedEvent {
  export type InputTuple = [
    amount: BigNumberish,
    totalReleased: BigNumberish,
    remaining: BigNumberish
  ];
  export type OutputTuple = [
    amount: bigint,
    totalReleased: bigint,
    remaining: bigint
  ];
  export interface OutputObject {
    amount: bigint;
    totalReleased: bigint;
    remaining: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [newPrice: BigNumberish, tokensMinted: BigNumberish];
  export type OutputTuple = [newPrice: bigint, tokensMinted: bigint];
  export interface OutputObject {
    newPrice: bigint;
    tokensMinted: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SettlementFailedEvent {
  export type InputTuple = [activationId: BigNumberish];
  export type OutputTuple = [activationId: bigint];
  export interface OutputObject {
    activationId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenomicsUpdatedEvent {
  export type InputTuple = [
    proofOfFaith: BigNumberish,
    xymMinted: BigNumberish,
    xymNextPrice: BigNumberish
  ];
  export type OutputTuple = [
    proofOfFaith: bigint,
    xymMinted: bigint,
    xymNextPrice: bigint
  ];
  export interface OutputObject {
    proofOfFaith: bigint;
    xymMinted: bigint;
    xymNextPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): PriceOracle;
  waitForDeployment(): Promise<this>;

  interface: PriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  COIN_DIVIDE: TypedContractMethod<[], [bigint], "view">;

  COIN_RELEASE_TARGET: TypedContractMethod<[], [bigint], "view">;

  COIN_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  GROWTH_FACTOR: TypedContractMethod<[], [bigint], "view">;

  NETWORK_FEE_PERCENT: TypedContractMethod<[], [bigint], "view">;

  PHI: TypedContractMethod<[], [bigint], "view">;

  SATOSHI_PRECISION: TypedContractMethod<[], [bigint], "view">;

  STARTING_PRICE: TypedContractMethod<[], [bigint], "view">;

  activateBulkTokens: TypedContractMethod<
    [tokensToActivate: BigNumberish],
    [void],
    "nonpayable"
  >;

  activateToken: TypedContractMethod<[], [void], "nonpayable">;

  activationCount: TypedContractMethod<[], [bigint], "view">;

  activationPrices: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  activationSettled: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  btcUsdPriceId: TypedContractMethod<[], [string], "view">;

  calculateBulkCost: TypedContractMethod<
    [tokensToActivate: BigNumberish],
    [bigint],
    "view"
  >;

  calculateNetworkFee: TypedContractMethod<
    [amount: BigNumberish],
    [bigint],
    "view"
  >;

  calculatePrice: TypedContractMethod<
    [_tokensMinted: BigNumberish],
    [bigint],
    "view"
  >;

  currentPrice: TypedContractMethod<[], [bigint], "view">;

  deactivateToken: TypedContractMethod<[], [void], "nonpayable">;

  getBtcPrice: TypedContractMethod<[], [bigint], "view">;

  getCoinDistributionStatus: TypedContractMethod<
    [],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        canReleaseCoins: boolean;
        nextReleaseAmount: bigint;
        releaseTarget: bigint;
        totalReleased: bigint;
        remaining: bigint;
      }
    ],
    "view"
  >;

  getCurrentPrice: TypedContractMethod<[], [bigint], "view">;

  getTokenomicsState: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        _proofOfFaith: bigint;
        _xymMinted: bigint;
        _xymNextPrice: bigint;
        _xymPrevPrice: bigint;
        _xyDivisor: bigint;
        _xyReleased: bigint;
        _xyRemaining: bigint;
        _xyReleaseTarget: bigint;
        _xyNextAmount: bigint;
      }
    ],
    "view"
  >;

  processActivationWithSettlement: TypedContractMethod<
    [settlementSuccess: boolean],
    [void],
    "nonpayable"
  >;

  proofOfFaith: TypedContractMethod<[], [bigint], "view">;

  pyth: TypedContractMethod<[], [string], "view">;

  setTokensMinted: TypedContractMethod<
    [_tokensMinted: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokensMinted: TypedContractMethod<[], [bigint], "view">;

  updatePrice: TypedContractMethod<[], [void], "nonpayable">;

  xyDivisor: TypedContractMethod<[], [bigint], "view">;

  xyNextAmount: TypedContractMethod<[], [bigint], "view">;

  xyReleaseTarget: TypedContractMethod<[], [bigint], "view">;

  xyReleased: TypedContractMethod<[], [bigint], "view">;

  xyRemaining: TypedContractMethod<[], [bigint], "view">;

  xymMinted: TypedContractMethod<[], [bigint], "view">;

  xymNextPrice: TypedContractMethod<[], [bigint], "view">;

  xymPrevPrice: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "COIN_DIVIDE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COIN_RELEASE_TARGET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "COIN_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "GROWTH_FACTOR"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "NETWORK_FEE_PERCENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PHI"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SATOSHI_PRECISION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "STARTING_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activateBulkTokens"
  ): TypedContractMethod<
    [tokensToActivate: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "activateToken"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activationCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "activationPrices"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "activationSettled"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "btcUsdPriceId"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "calculateBulkCost"
  ): TypedContractMethod<[tokensToActivate: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculateNetworkFee"
  ): TypedContractMethod<[amount: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "calculatePrice"
  ): TypedContractMethod<[_tokensMinted: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deactivateToken"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBtcPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCoinDistributionStatus"
  ): TypedContractMethod<
    [],
    [
      [boolean, bigint, bigint, bigint, bigint] & {
        canReleaseCoins: boolean;
        nextReleaseAmount: bigint;
        releaseTarget: bigint;
        totalReleased: bigint;
        remaining: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCurrentPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTokenomicsState"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        _proofOfFaith: bigint;
        _xymMinted: bigint;
        _xymNextPrice: bigint;
        _xymPrevPrice: bigint;
        _xyDivisor: bigint;
        _xyReleased: bigint;
        _xyRemaining: bigint;
        _xyReleaseTarget: bigint;
        _xyNextAmount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "processActivationWithSettlement"
  ): TypedContractMethod<[settlementSuccess: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "proofOfFaith"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pyth"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setTokensMinted"
  ): TypedContractMethod<[_tokensMinted: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tokensMinted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "xyDivisor"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xyNextAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xyReleaseTarget"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xyReleased"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xyRemaining"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xymMinted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xymNextPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "xymPrevPrice"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ActivationProcessed"
  ): TypedContractEvent<
    ActivationProcessedEvent.InputTuple,
    ActivationProcessedEvent.OutputTuple,
    ActivationProcessedEvent.OutputObject
  >;
  getEvent(
    key: "CoinsReleased"
  ): TypedContractEvent<
    CoinsReleasedEvent.InputTuple,
    CoinsReleasedEvent.OutputTuple,
    CoinsReleasedEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SettlementFailed"
  ): TypedContractEvent<
    SettlementFailedEvent.InputTuple,
    SettlementFailedEvent.OutputTuple,
    SettlementFailedEvent.OutputObject
  >;
  getEvent(
    key: "TokenomicsUpdated"
  ): TypedContractEvent<
    TokenomicsUpdatedEvent.InputTuple,
    TokenomicsUpdatedEvent.OutputTuple,
    TokenomicsUpdatedEvent.OutputObject
  >;

  filters: {
    "ActivationProcessed(uint256,uint256,bool)": TypedContractEvent<
      ActivationProcessedEvent.InputTuple,
      ActivationProcessedEvent.OutputTuple,
      ActivationProcessedEvent.OutputObject
    >;
    ActivationProcessed: TypedContractEvent<
      ActivationProcessedEvent.InputTuple,
      ActivationProcessedEvent.OutputTuple,
      ActivationProcessedEvent.OutputObject
    >;

    "CoinsReleased(uint256,uint256,uint256)": TypedContractEvent<
      CoinsReleasedEvent.InputTuple,
      CoinsReleasedEvent.OutputTuple,
      CoinsReleasedEvent.OutputObject
    >;
    CoinsReleased: TypedContractEvent<
      CoinsReleasedEvent.InputTuple,
      CoinsReleasedEvent.OutputTuple,
      CoinsReleasedEvent.OutputObject
    >;

    "PriceUpdated(uint256,uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "SettlementFailed(uint256)": TypedContractEvent<
      SettlementFailedEvent.InputTuple,
      SettlementFailedEvent.OutputTuple,
      SettlementFailedEvent.OutputObject
    >;
    SettlementFailed: TypedContractEvent<
      SettlementFailedEvent.InputTuple,
      SettlementFailedEvent.OutputTuple,
      SettlementFailedEvent.OutputObject
    >;

    "TokenomicsUpdated(uint256,uint256,uint256)": TypedContractEvent<
      TokenomicsUpdatedEvent.InputTuple,
      TokenomicsUpdatedEvent.OutputTuple,
      TokenomicsUpdatedEvent.OutputObject
    >;
    TokenomicsUpdated: TypedContractEvent<
      TokenomicsUpdatedEvent.InputTuple,
      TokenomicsUpdatedEvent.OutputTuple,
      TokenomicsUpdatedEvent.OutputObject
    >;
  };
}
