/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC6551Account,
  IERC6551AccountInterface,
} from "../../../contracts/XMBLToken.sol/IERC6551Account";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "executeCall",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IERC6551Account__factory {
  static readonly abi = _abi;
  static createInterface(): IERC6551AccountInterface {
    return new Interface(_abi) as IERC6551AccountInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC6551Account {
    return new Contract(address, _abi, runner) as unknown as IERC6551Account;
  }
}
